export const cinemas = [
    {
        id: 1,
        name: "Cinestar Quốc Thanh",
        address: "271 Nguyễn Trãi, P. Nguyễn Cư Trinh, Q.1",
        province_id: 1,
    },
    {
        id: 2,
        name: "Cinestar Hai Bà Trưng",
        address: "135 Hai Bà Trưng, P. Bến Nghé, Q.1",
        province_id: 1,
    },
    {
        id: 3,
        name: "Galaxy Nguyễn Du",
        address: "116 Nguyễn Du, Q.1",
        province_id: 1,
    },
    {
        id: 4,
        name: "Galaxy Tân Bình",
        address: "246 Nguyễn Hồng Đào, Q.Tân Bình",
        province_id: 1,
    },
    {
        id: 5,
        name: "Galaxy Quang Trung",
        address: "Lầu 3, CoopMart Foodcosa, 304A Quang Trung, P.11, Q. Gò Vấp",
        province_id: 1,
    },
    {
        id: 6,
        name: "Galaxy Trung Chánh",
        address: "Trung Tâm Văn Hóa Quận 12, 09 Quốc lộ 22, P. Trung Mỹ Tây, Q.12",
        province_id: 1,
    },
    {
        id: 7,
        name: "Galaxy Nguyễn Văn Quá",
        address: "119B Nguyễn Văn Quá, P. Đông Hưng Thuận, Q.12, Tp. Hồ Chí Minh",
        province_id: 1,
    },
    {
        id: 8,
        name: "Galaxy Co.opXtra Linh Trung",
        address: "Siêu thị Co.opXtra Thủ Đức 934 QL1A, Phường Linh Trung, Thành phố Thủ Đức",
        province_id: 1,
    },
    {
        id: 9,
        name: "Galaxy Sala",
        address: "Tầng 3, Thiso Mall Sala, 10 Mai Chí Thọ, Phường Thủ Thiêm, Thành phố Thủ Đức",
        province_id: 1,
    },
    {
        id: 10,
        name: "CGV CT Plaza",
        address: "Tầng 10, CT Plaza, 60A Trường Sơn, P.2, Q. Tân Bình",
        province_id: 1,
    },
    {
        id: 11,
        name: "CGV Hùng Vương Plaza",
        address: "Tầng 7, Hùng Vương Plaza, 126 Hùng Vương, Q.5",
        province_id: 1,
    },
    {
        id: 12,
        name: "CGV Thảo Điền Pearl",
        address: "Tầng 2, Thảo Điền Mall, 12 Quốc Hương, P. Thảo Điền, Q.2",
        province_id: 1,
    },
    {
        id: 13,
        name: "CGV Liberty Citypoint",
        address: "Tầng M - 1, Liberty Center Saigon Citypoint, 59 - 61 Pasteur, Q.1",
        province_id: 1,
    },
    {
        id: 14,
        name: "CGV Vincom Thủ Đức",
        address: "Tầng 5, TTTM Vincom Thủ Đức, 216 Võ Văn Ngân, P. Bình Thọ, Q. Thủ Đức",
        province_id: 1,
    },
    {
        id: 15,
        name: "CGV Vincom Gò Vấp",
        address: "Tầng 5 TTTM Vincom Plaza Gò Vấp, 12 Phan Văn Trị, P.7, Q. Gò Vấp",
        province_id: 1,
    },
    {
        id: 16,
        name: "CGV Pearl Plaza",
        address: "Tầng 5, Pearl Plaza, 561A Điện Biên Phủ, P.25, Q. Bình Thạnh",
        province_id: 1,
    },
    {
        id: 17,
        name: "CGV Hoàng Văn Thụ",
        address: "Tầng 1 và 2, Gala Center, số 415, Hoàng Văn Thụ, Phường 2, Quận Tân Bình",
        province_id: 1,
    },
    {
        id: 18,
        name: "CGV Vincom Đồng Khởi",
        address: "Tầng 3, TTTM Vincom Center Đồng Khởi, 72 Lê Thánh Tôn & 45A Lý Tự Trọng, Quận 1",
        province_id: 1,
    },
    {
        id: 19,
        name: "CGV Saigonres Nguyễn Xí",
        address: "Tầng 4-5, Saigonres Plaza, 79/81 Nguyễn Xí, P 26, Q Bình Thạnh",
        province_id: 1,
    },
    {
        id: 20,
        name: "CGV Sư Vạn Hạnh",
        address: "Tầng 6, Vạn Hạnh Mall, 11 Sư Vạn Hạnh Q. 10",
        province_id: 1,
    },
    {
        id: 21,
        name: "CGV Vincom Landmark 81",
        address: "B1, Vincom Center Landmark 81, 722 Điện Biên Phủ, P. 22, Q. Bình Thạnh",
        province_id: 1,
    },
    {
        id: 22,
        name: "CGV Giga Mall Thủ Đức",
        address: "Tầng 6 TTTM GIGAMALL, 240-242 Phạm Văn Đồng, P. Hiệp Bình Chánh, Q. Thủ Đức",
        province_id: 1,
    },
    {
        id: 23,
        name: "CGV Lý Chính Thắng",
        address: "Tầng 3 Cao ốc Intresco Plaza - 83 Lý Chính Thắng, Phường 8, Quận 3",
        province_id: 1,
    },
    {
        id: 24,
        name: "Cinestar Sinh Viên",
        address: "Nhà Văn hóa Sinh viên Đại học Quốc gia TP.HCM, P. Đông Hòa, TP. Dĩ An",
        province_id: 2,
    },
    {
        id: 25,
        name: "CGV Bình Dương Square",
        address: "Tầng 3 Bình Dương Square, Số 1 Phú Lợi, P. Phú Lợi",
        province_id: 2,
    },
    {
        id: 26,
        name: "CGV Aeon Canary",
        address: "Tầng 2, AEON – Bình Dương Canary, Đại lộ Bình Dương, P. Bình Hòa, TP. Thuận An",
        province_id: 2,
    },
    {
        id: 27,
        name: "CGV Coopmart Biên Hòa",
        address: "Tầng 3, Khu Siêu thị Co-op Mart 121 Phạm Văn Thuận, P. Tân Tiến, Tp. Biên Hoà",
        province_id: 3,
    },
    {
        id: 28,
        name: "CGV BigC Đồng Nai",
        address: "Siêu thị BigC Đồng Nai, Khu phố 1, P. Long Bình Tân, Tp. Biên Hòa",
        province_id: 3,
    },
];
