export const films = [
    {
        id: 1,
        name: `BOCCHI THE ROCK! Recap Part 1`,
        description: `Hitori Gotoh, hay còn gọi là "Bocchi-chan", là một cô gái cực kỳ nhút nhát và luôn e ngại khi tiếp xúc với người khác. Mỗi khi nói chuyện, cô thường bắt đầu với câu “À...”. Khi còn học cấp hai, cô bắt đầu học guitar vì mong muốn tham gia một ban nhạc. Cô nghĩ rằng, nhờ chơi nhạc, ngay cả một người nhút nhát như mình cũng có thể tỏa sáng. Nhưng vì không có bạn, cô chỉ có thể tập đàn một mình mỗi ngày suốt 6 tiếng. Sau khi trở thành một tay guitar giỏi, cô đăng các video chơi đàn lên mạng dưới tên “Guitar Hero” và luôn mơ mộng về việc biểu diễn tại lễ hội trường. Tuy nhiên, cô không tìm được ai để cùng lập ban nhạc, và rồi cô nhận ra mình đã lên cấp ba mà vẫn chưa kết bạn được với ai! Cô gần như trở thành một người sống thu mình, nhưng một ngày nọ, Nijika Ijichi, tay trống của ban nhạc Kessoku, đã tìm đến cô. Từ đó, cuộc sống hàng ngày của cô bắt đầu thay đổi từng chút một...`,
        release_date: `11/10/2024`,
        duration: 90,
        age_rating: "K",
        genres: "Hoạt hình",
        directors: "Keiichiro Saito",
        actors: "Yoshino Aoyama; Sayumi Suzushiro; Saku Mizuno; Ikumi Hasegawa",
        lang: "Tiếng Nhật",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/3/5/350x495-bocchi-p1.jpg",
        trailer: "https://www.youtube.com/watch?v=JfgIbMV7q0Y",
        status_id: 0,
    },
    {
        id: 2,
        name: `BOCCHI THE ROCK! Recap Part 2`,
        description: `Manga 4 khung tranh nổi tiếng của Aki Hamazi, Bocchi the Rock!, lần đầu được đăng trên tạp chí Manga Time Kirara Max của Houbunsha. Câu chuyện xoay quanh Hitori Gotoh, một cô gái cực kỳ nhút nhát và lo lắng khi giao tiếp xã hội, đã tham gia vào ban nhạc tên là Kessoku Band và dần trưởng thành bên cạnh ba người bạn cùng ban nhạc lập dị của mình: Nijika Ijichi, Ryo Yamada và Ikuyo Kita. Câu chuyện này đã chạm đến trái tim của rất nhiều người. Khi anime bắt đầu phát sóng vào mùa thu năm 2022, nó nhanh chóng trở nên cực kỳ nổi tiếng, đặc biệt là trong giới trẻ. Bộ phim đã giành được nhiều giải thưởng và nhận được sự ủng hộ nồng nhiệt từ người hâm mộ trong nước và quốc tế. Âm nhạc của phim cũng gây tiếng vang lớn, với album "Kessoku Band" của ban nhạc xếp hạng số 1 trên bảng xếp hạng album kỹ thuật số của Oricon năm 2023 và đứng đầu bảng xếp hạng album tải về của Billboard Nhật Bản. Câu chuyện về Kessoku Band, với sự thành công vang dội cả về anime lẫn âm nhạc, sẽ ra rạp vào năm 2024 dưới dạng một bộ phim tổng hợp từ loạt phim TV, với hiệu ứng hình ảnh và âm thanh mạnh mẽ trên màn ảnh lớn! Nếu bạn là người hướng nội, hãy thử sức với rock!`,
        release_date: `18/10/2024`,
        duration: 75,
        age_rating: "K",
        genres: "Hoạt hình",
        directors: "Keiichiro Saito",
        actors: "Yoshino Aoyama; Sayumi Suzushiro; Saku Mizuno; Ikumi Hasegawa",
        lang: "Tiếng Nhật",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/3/5/350x495-bocchi-p2.jpg",
        trailer: "https://www.youtube.com/watch?v=as4D2VOj_BI",
        status_id: 0,
    },
    {
        id: 3,
        name: `CƯỜI XUYÊN BIÊN GIỚI`,
        description: `Cười Xuyên Biên Giới kể về hành trình của Jin-bong (Ryu Seung-ryong) - cựu vô địch bắn cung quốc gia, sau khi nghỉ hưu, anh đã trở thành một nhân viên văn phòng bình thường. Đứng trước nguy cơ bị sa thải, Jin-bong phải nhận một nhiệm vụ bất khả thi là bay đến nửa kia của trái đất trong nỗ lực tuyệt vọng để sinh tồn. Sống sót sau một sự cố đe doạ tính mạng, Jin-bong đã “hạ cánh” xuống khu rừng Amazon, nơi anh gặp bộ ba thổ dân bản địa có kỹ năng bắn cung thượng thừa: Sika, Eeba và Walbu. Tin rằng đã tìm ra cách để tự cứu mình, Jin-bong hợp tác với phiên dịch ngáo ngơ Bbang-sik (Jin Sun-kyu) và đưa ba chiến thần cung thủ đến Hàn Quốc cho một nhiệm vụ táo bạo.`,
        release_date: `15/11/2024`,
        duration: 113,
        age_rating: "T13",
        genres: "Hài",
        directors: "KIM Chang-ju",
        actors: "Ryu Seung-ryong , Jin Sun-kyu, Igor Rafael P EDROSO, Luan B RUM DE ABREU E LIMA, JB João Batista GOMES DE O LIVEIRA, Yeom Hye-ran và Go Kyoung- pyo, Lee Soon-won",
        lang: "Tiếng Hàn",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/c5f0a1eff4c394a251036189ccddaacd/a/m/amazon-main-poster-printing.jpg",
        trailer: "https://www.youtube.com/watch?v=jxcKe1I4HtQ",
        status_id: 0,
    },
    {
        id: 4,
        name: `VÕ SĨ GIÁC ĐẤU II`,
        description: `Sau khi đánh mất quê hương vào tay hoàng đế bạo chúa – người đang cai trị Rome, Lucius trở thành nô lệ giác đấu trong đấu trường Colosseum và phải tìm kiếm sức mạnh từ quá khứ để đưa vinh quang trở lại cho người dân Rome.`,
        release_date: `15/11/2024`,
        duration: 148,
        age_rating: "T18",
        genres: "Hành Động, Phiêu Lưu, Tâm Lý",
        directors: "Ridley Scott",
        actors: "Paul Mescal, Joseph Quinn, Pedro Pascal, Connie Nielsen, Denzel Washington,…",
        lang: "Tiếng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/c5f0a1eff4c394a251036189ccddaacd/7/0/700x1000-gladiator.jpg",
        trailer: "https://www.youtube.com/watch?v=R4AFSgUGEEs",
        status_id: 0,
    },
    {
        id: 5,
        name: `MẬT MÃ ĐỎ`,
        description: `Sau khi Ông già Noel (mật danh: Red One) bị bắt cóc, Trưởng An ninh Bắc Cực (Dwayne Johnson) phải hợp tác với thợ săn tiền thưởng khét tiếng nhất thế giới (Chris Evans) trong một nhiệm vụ kịch tính xuyên lục địa để giải cứu Giáng Sinh.`,
        release_date: `2024-11-08`,
        duration: 125,
        age_rating: "K",
        genres: "Hài, Hành Động, Phiêu Lưu",
        directors: "Jake Kasdan",
        actors: "Dwayne Johnson; Chris Evans; Lucy Liu",
        lang: "Tiếng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/1800x/71252117777b696995f01934522c402d/r/s/rsz_redone_insta_vert_main_1638x2048_intl.jpg",
        trailer: "https://www.youtube.com/watch?v=2T_mKyH17mY",
        status_id: 0,
    },
    {
        id: 6,
        name: `ĐÔI BẠN HỌC YÊU`,
        description: `Bộ phim xoay quanh đôi bạn ngỗ nghịch Jae-hee và Heung-soo cùng những khoảnh khắc “dở khóc dở cười” khi cùng chung sống trong một ngôi nhà. Jae-hee là một cô gái “cờ xanh” với tâm hồn tự do, sống hết mình với tình yêu. Ngược lại, Heung-soo lại là một “cờ đỏ” chính hiệu khi cho rằng tình yêu là sự lãng phí cảm xúc không cần thiết. Bỏ qua những tin đồn lan tràn do người khác tạo ra, Jae-hee và Heung-soo chọn sống chung nhưng yêu theo cách riêng của họ. Hai quan điểm tình yêu trái ngược sẽ đẩy cả hai sang những ngã rẽ và kết cục khác nhau. Sau cùng, Jae-hee hay Heung-soo sẽ về đích trong hành trình “học yêu” này?`,
        release_date: `2024-11-08`,
        duration: 118,
        age_rating: "T18",
        genres: "Hài, Tình cảm",
        directors: "E.Oni",
        actors: "Kim Go Eun, Steve Sanghyun Noh",
        lang: "Tiếng Hàn",
        format: "2D",
        poster: "https://www.elle.vn/app/uploads/2024/10/17/613971/Teaser-Poster-phim-doi-ban-hoc-yeu-scaled.jpg",
        trailer: "https://www.youtube.com/watch?v=EIARKqcXILM",
        status_id: 0,
    },
    {
        id: 7,
        name: `NGÀY XƯA CÓ MỘT CHUYỆN TÌNH`,
        description: `Ngày Xưa Có Một Chuyện Tình xoay quanh câu chuyện tình bạn, tình yêu giữa hai chàng trai và một cô gái từ thuở ấu thơ cho đến khi trưởng thành, phải đối mặt với những thử thách của số phận. Trải dài trong 4 giai đoạn từ năm 1987 - 2000, ba người bạn cùng tuổi - Vinh, Miền, Phúc đã cùng yêu, cùng bỡ ngỡ bước vào đời, va vấp và vượt qua.`,
        release_date: `2024-10-28`,
        duration: 135,
        age_rating: "T16",
        genres: "Tình cảm",
        directors: "Trịnh Đình Lê Minh",
        actors: "Avin Lu, Ngọc Xuân, Đỗ Nhật Hoàng, Thanh Tú, Bảo Tiên, Hạo Khang",
        lang: "Tiếng Việt",
        format: "2D",
        poster: "https://cdn.tuoitre.vn/471584752817336320/2024/4/16/first-look-poster-1713248286753396686888.jpg",
        trailer: "https://www.youtube.com/watch?v=qaeHlk0OXec",
        status_id: 0,
    },
    {
        id: 8,
        name: `NGUYỄN VĂN MƯỜI`,
        description: `Mitsuha – một nữ sinh sống tại vùng quê Nhật Bản, chán ngán cuộc sống hiện tại và luôn mong được lên Tokyo sống. Taki – một cậu nam sinh ở Tokyo, làm thêm tại một nhà hàng Ý sau giờ học, thích vẽ vời và quan tâm đến ngành kiến trúc. Cả hai bắt đầu có những giấc mơ kỳ lạ kể từ khi ngôi sao chổi Tiamat huyền thoại xuất hiện trên bầu trời. Trong mơ, Mitsuha mơ thành một cậu nam sinh ở Tokyo còn Taki mơ mình là một cô nữ sinh ở vùng quê Nhật Bản. Và họ nhanh chóng nhận ra mình đã bị hoán đổi cơ thể. Để tránh những rắc rối, họ để lại cho nhau những lời nhắn, những quy định yêu cầu người kia không được làm gì. Mọi việc cứ thế trôi qua, cho đến buổi tối khi ngôi sao chổi đi qua và tách ra một phần rơi xuống Nhật Bản, cũng từ đó Taki phát hiện cậu và Mitsuha không còn hoán đổi cho nhau nữa.`,
        release_date: `2017-01-13`,
        duration: 106,
        age_rating: "T13",
        genres: "Hoạt hình, Tình cảm",
        directors: "Makoto Shinkai",
        actors: "Ryunosuke Kamiki, Mone Kamishiraishi, Ryo Narita, Aoi Yûki, Nobunaga Shimazaki",
        lang: "Tiếng Nhật",
        format: "2D",
        poster: "https://m.media-amazon.com/images/M/MV5BNmEyZjI0M2MtNGFkOC00YTRlLWI0MGQtYTgyODY2MGRhMjc4XkEyXkFqcGc@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=5SUXmUFwnuY",
        status_id: 0,
    },
    {
        id: 9,
        name: `DÁNG HÌNH THANH ÂM`,
        description: `Cậu học trò Shoya Ishida bị bạn bè và thầy cô cô lập vì đã bắt nạt cô bạn cùng lớp bị điếc bẩm sinh Shoko Nishimiya đến nỗi cô bạn phải chuyển trường. Sự cô lập này kéo dài đến tận cấp 3 khiến Shoya không có bạn và thậm chí định tự tử. Tình cờ, Shoya gặp lại Shoko và nhận ra cô bạn vẫn đơn độc. Shoya quyết định chuộc lại lỗi lầm năm xưa bằng cách giúp Shoko kết nối với những người bạn học cũ. Dần dần, giữa họ nảy sinh những tình cảm trong sáng hồn nhiên tuổi học trò.`,
        release_date: `2017-05-12`,
        duration: 129,
        age_rating: "P",
        genres: "Hoạt hình, Tình cảm",
        directors: "Naoko Yamada",
        actors: "Miyu Irino, Saori Hayami, Aoi Yuki, Kensho Ono, Yuki Kaneko",
        lang: "Tiếng Nhật",
        format: "2D",
        poster: "https://upload.wikimedia.org/wikipedia/vi/c/c6/Koe_no_Katachi_Film_Poster.jpg",
        trailer: "https://www.youtube.com/watch?v=FGcKqIQjRSY",
        status_id: 0,
    },
    {
        id: 10,
        name: `SPY×FAMILY CODE: White`,
        description: `Bộ phim là phần phim điện ảnh của series anime nổi tiếng Spy x Family. Trong bộ phim lần này, sau khi nhận được yêu cầu thay thế mình trong Chiến dịch Strix, Loid Forger quyết định giúp con gái Anya chiến thắng trong cuộc thi nấu ăn tại Học viện Eden bằng cách nấu bữa ăn yêu thích của hiệu trưởng để tránh bị thay thế khỏi nhiệm vụ mật. Nhưng từ đây, gia đình Forger phát hiện ra bí mật kinh hoàng ảnh hưởng đến hòa bình thế giới`,
        release_date: `2024-02-10`,
        duration: 111,
        age_rating: "T13",
        genres: "Hài, Hành Động, Hoạt Hình",
        directors: "Kazuhiro Furuhashi",
        actors: "Atsumi Tanezaki, Takuya Eguchi, Saori Hayami,…",
        lang: "Tiếng Nhật",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/a/p/approved_main_art.jpg",
        trailer: "https://www.youtube.com/watch?v=Nf3bt111lVo",
        status_id: 0,
    },
    {
        id: 11,
        name: `THÁM TỬ LỪNG DANH CONAN: NGÔI SAO 5 CÁNH 1 TRIỆU ĐÔ`,
        description: `Trong khi đến Hakodate tham gia một giải kiếm đạo, Conan và Heiji đụng độ siêu trộm Kaito Kid - khi hắn đang nhắm tới một thanh kiếm Nhật được cất giấu trong nhà kho của một gia đình tài phiệt. Thi thể một tay buôn vũ khí khét tiếng được phát hiện với vết chém hình chữ thập, và trùng hợp thay, "kho báu" mà gã truy lùng dường như cũng có liên quan mật thiết đến thanh kiếm cổ mà Kid đang nhắm tới.`,
        release_date: `2024-08-02`,
        duration: 111,
        age_rating: "T13",
        genres: "Bí ẩn, Hoạt Hình, Tình cảm",
        directors: "Chika Nagaoka",
        actors: "Rikiya Koyama, Minami Takayama, Kenjirô Tsuda, Wakana Yamazaki",
        lang: "Tiếng Nhật",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/2/4/240531_-_dc27_-_main_poster_1_.jpg",
        trailer: "https://www.youtube.com/watch?v=C4pG3GbhQZw",
        status_id: 0,
    },
    {
        id: 12,
        name: `KẺ TRỘM MẶT TRĂNG 4`,
        description: `Gru phải đối mặt với kẻ thù mới là Maxime Le Mal và Valentina đang lên kế hoạch trả thù anh, buộc gia đình anh phải lẩn trốn đi nơi khác. Bên cạnh việc đấu tranh bảo vệ gia đình, Gru đồng thời còn phải tìm ra điểm chung với thành viên mới nhất trong nhà đó là Gru Jr.`,
        release_date: `2024-07-05`,
        duration: 94,
        age_rating: "P",
        genres: "Hài, Hoạt Hình, Phiêu Lưu",
        directors: "Chris Renaud, Patrick Delage",
        actors: "Steve Carell, Kristen Wiig, Joey King",
        lang: "Tiếng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/d/m/dm4_posterminion_700x1000.jpg",
        trailer: "https://www.youtube.com/watch?v=8nBoEAkM0Rc",
        status_id: 0,
    },
    {
        id: 13,
        name: `VENOM: KÈO CUỐI`,
        description: `Đây là phần phim cuối cùng và hoành tráng nhất về cặp đôi Venom và Eddie Brock (Tom Hardy). Sau khi dịch chuyển từ Vũ trụ Marvel trong ‘Spider-man: No way home’ (2021) trở về thực tại, Eddie Brock giờ đây cùng Venom sẽ phải đối mặt với ác thần Knull hùng mạnh - kẻ tạo ra cả chủng tộc Symbiote và những thế lực đang rình rập khác. Cặp đôi Eddie và Venom sẽ phải đưa ra lựa quyết định khốc liệt để hạ màn kèo cuối này.`,
        release_date: `2024-10-25`,
        duration: 109,
        age_rating: "T13",
        genres: "Hành Động, Khoa Học Viễn Tưởng, Phiêu Lưu, Thần thoại",
        directors: "Kelly Marcel",
        actors: "Tom Hardy, Juno Temple, Chiwetel Ejiofor, Clark Backo, Stephen Graham",
        lang: "Tiếng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/r/s/rsz_vnm3_intl_online_1080x1350_tsr_01.jpg",
        trailer: "https://www.youtube.com/watch?v=id1rfr_KZWg",
        status_id: 0,
    },
    {
        id: 14,
        name: `ROBOT HOANG DÃ`,
        description: `Cuộc phiêu lưu hoành tráng theo chân hành trình của một robot — đơn vị ROZZUM 7134, gọi tắt là Roz. Roz vô tình dạt vào hoang đảo sau một sự cố và nơi đây trở thành địa điểm sống mới của cô. Tại đây, Roz kết thân và nhận nuôi một chú ngỗng con, đặt tên là Brightbill. Roz và Brightbill dần dần thân thiết với các bạn thú trên đảo, song sau đó phải chống chọi, bảo vệ “nhà mới” trước sự xâm lăng của nhà máy từng sản xuất ra Roz.`,
        release_date: `2024-10-11`,
        duration: 102,
        age_rating: "P",
        genres: "Gia đình, Hoạt Hình, Khoa Học Viễn Tưởng, Phiêu Lưu",
        directors: "Chris Sanders",
        actors: "Lupita Nyong'o, Pedro Pascal, Catherine O’hara, Bill Nighy,…",
        lang: "Tiếng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/w/r/wrb_intl1sht_headtouch4_rgb_700x1000.jpg",
        trailer: "https://www.youtube.com/watch?v=2l8_FNIBWLM",
        status_id: 0,
    },
    {
        id: 15,
        name: `HỌC VIỆN ANH HÙNG: YOU’RE NEXT`,
        description: `Vào mùa xuân năm thứ hai, trong khi Nhật Bản đang bị tàn phá bởi các cuộc chiến, một người đàn ông bí ẩn bất ngờ xuất hiện có tên là Dark Might. Đối mặt với Deku và những người bạn, hắn tự xưng mình là biểu tượng mới thay thế All Might với tuyên bố hùng hồn: "Tiếp theo là đến lượt ta!". Với dã tâm của mình, Dark Might sử dụng năng lực để tạo ra một pháo đài khổng lồ và nhốt người dân cùng anh hùng vào đó. Deku, Bakugo, Todoroki cùng lớp 1-A của trường U.A. dũng cảm đối đầu với Dark Might và tổ chức tội phạm bí ẩn do hắn cầm đầu, mang tên "Gia đình Gollini". Liệu họ có thể ngăn chặn tham vọng của biểu tượng mới Dark Might và bảo vệ thế giới?`,
        release_date: `2024-11-08`,
        duration: 110,
        age_rating: "K",
        genres: "Hoạt Hình",
        directors: "Tensai Okamura",
        actors: "Van Barr Jr. - Nasim Benelkour - Gerard Caster",
        lang: "Tiếng Nhật",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/3/5/350x495-academia.jpg",
        trailer: "https://www.youtube.com/watch?v=O_JcwpDergM",
        status_id: 0,
    },
    {
        id: 16,
        name: `CÔ DÂU HÀO MÔN`,
        description: `Phim lấy đề tài làm dâu hào môn và khai thác câu chuyện môn đăng hộ đối, lối sống và quy tắc của giới thượng lưu dưới góc nhìn hài hước và châm biếm.`,
        release_date: `2024-10-18`,
        duration: 114,
        age_rating: "T18",
        genres: "Tâm Lý",
        directors: "Vũ Ngọc Đãng",
        actors: "Uyển Ân, Samuel An, Thu Trang, Lê Giang, Kiều Minh Tuấn, NSND Hồng Vân,…",
        lang: "Tiếng Việt",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/c/g/cgv_457x590.jpg",
        trailer: "https://www.youtube.com/watch?v=QJ8E9R70csY",
        status_id: 0,
    },
    {
        id: 17,
        name: `WICKED`,
        description: `Cho dù là tiểu thư xinh đẹp Galinda hay phù thủy da xanh Elphaba thì ai cũng có một giấc mơ của riêng mình. Xem ngay trailer của bom tấn điện ảnh màu nhiệm bậc nhất màn bạc mùa lễ hội WICKED! WICKED | Dự kiến khởi chiếu: 29.11.2024`,
        release_date: `2024-11-22`,
        duration: 161,
        age_rating: "K",
        genres: "Nhạc kịch, Thần thoại, Tình cảm",
        directors: "Jon M. Chu",
        actors: "Cynthia Erivo, Ariana Grande, Jonathan Bailey",
        lang: "Tiếng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/w/k/wkd_forestduo_470x700.jpg",
        trailer: "https://www.youtube.com/watch?v=IILf3ZEBnmM",
        status_id: 0,
    },
    {
        id: 18,
        name: `SẮC MÀU CỦA CẢM XÚC`,
        description: `Một tình bạn chớm nở giữa những kẻ lạc loài khi Tosuko, nữ sinh sở hữu khả năng nhìn thấy màu sắc trong cảm xúc của người khác tham gia một ban nhạc với hai thiếu niên là Kimi và Rui.`,
        release_date: `2024-11-22`,
        duration: 102,
        age_rating: "P",
        genres: "Hoạt Hình, Tâm Lý",
        directors: "Naoko Yamada",
        actors: "Sayu Suzukawa, Akari Takaishi, Taisei Kido, ...",
        lang: "Tiếng Nhật",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/p/o/poster_main_sac_mau_cua_cam_xuc_1_.jpg",
        trailer: "https://www.youtube.com/watch?v=ammgfic1zwA",
        status_id: 0,
    },
    {
        id: 19,
        name: `HÀNH TRÌNH CỦA MOANA 2`,
        description: `“Hành Trình của Moana 2” là màn tái hợp của Moana và Maui sau 3 năm, trở lại trong chuyến phiêu lưu cùng với những thành viên mới. Theo tiếng gọi của tổ tiên, Moana sẽ tham gia cuộc hành trình đến những vùng biển xa xôi của Châu Đại Dương và sẽ đi tới vùng biển nguy hiểm, đã mất tích từ lâu. Cùng chờ đón cuộc phiêu lưu của Moana đầy chông gai sắp tới vào 29.11.2024.`,
        release_date: `2024-11-29`,
        duration: 0,
        age_rating: "T13",
        genres: "Hành Động, Hoạt Hình, Phiêu Lưu, Thần thoại",
        directors: "David G. Derrick Jr.",
        actors: "Auli‘i Cravalho, Dwayne Johnson, Rachel House, Temuera Morrison, Nicole Scherzinger, Hualālai Chung, David Fane, Rose Matafeo, Awhimai Fraser, Gerald Ramsey, Khaleesi Lambert-Tsuda",
        lang: "Tiếng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/c/g/cgv_800x1200.jpg",
        header_poster: "https://cdn.galaxycine.vn/media/2024/12/4/moana-2-750_1733308287728.jpg",
        trailer: "https://www.youtube.com/watch?v=cBG30KsGRH8",
        status_id: 0,
    },
    {
        id: 20,
        name: `NHÍM SONIC 3`,
        description: `Sonic và nhóm bạn mới của anh phải đối mặt với một thách thức mới: bảo vệ ngôi làng của mình khỏi sự tấn công của Dr. Robotnik và Knuckles, người đang tìm kiếm nhẫn quý Master Emerald để thống trị thế giới.`,
        release_date: `2024-12-27`,
        duration: 0,
        age_rating: "",
        genres: "Gia đình, Hài, Hành Động, Phiêu Lưu, Thần thoại",
        directors: "Jeff Fowler",
        actors: "Ben Schwartz, Colleen O'Shaughnessey, Idris Elba",
        lang: "Tiếng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/s/t/sth3_poster_470x700.jpg",
        trailer: "https://www.youtube.com/watch?v=A6SxA_JIE68",
        status_id: 1,
    },
    {
        id: 21,
        name: `KÍNH VẠN HOA`,
        description: `Sau sự thành công của hai phim điện ảnh chuyển thể từ hai tác phẩm đình đám của nhà văn Nguyễn Nhật Ánh, một tác phẩm nổi bật khác của nhà văn hiện đại thành công nhất Việt Nam chuẩn bị được đưa lên màn ảnh rộng: “Kính Vạn Hoa”. Và đạo diễn dự án bom tấn này là “đạo diễn trăm tỷ” Võ Thanh Hòa.`,
        release_date: `2024-12-13`,
        duration: 0,
        age_rating: "",
        genres: "Hài, Phiêu Lưu",
        directors: "Võ Thanh Hòa",
        actors: "",
        lang: "Tiếng Việt",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/d/_/d_n_k_nh_v_n_hoa_1_.jpg",
        trailer: "https://www.youtube.com/watch?v=6z1BoUbB-fs",
        status_id: 1,
    },
    {
        id: 22,
        name: `CHÚA TỂ CỦA NHỮNG CHIẾC NHẪN: CUỘC CHIẾN CỦA ROHIRRIM`,
        description: `Lấy bối cảnh 183 năm trước những sự kiện trong bộ ba phim gốc, “Chúa Tể Của Những Chiếc Nhẫn: Cuộc Chiến Của Rohirrim" kể về số phận của Gia tộc của Helm Hammerhand, vị vua huyền thoại của Rohan. Cuộc tấn công bất ngờ của Wulf, lãnh chúa xảo trá và tàn nhẫn của tộc Dunlending, nhằm báo thù cho cái chết của cha hắn, đã buộc Helm và thần dân của ngài phải chống cự trong pháo đài cổ Hornburg - một thành trì vững chãi sau này được biết đến với tên gọi Helm's Deep. Tình thế ngày càng tuyệt vọng, Héra, con gái của Helm, phải dốc hết sức dẫn dắt cuộc chiến chống lại kẻ địch nguy hiểm, quyết tâm tiêu diệt bọn chúng.`,
        release_date: `2024-12-13`,
        duration: 0,
        age_rating: "",
        genres: "Hành Động, Hoạt Hình, Phiêu Lưu, Thần thoại",
        directors: "Kenji Kamiyama",
        actors: "Brian Cox, Gaia Wise, Luke Pasqualino, Miranda Otto,…",
        lang: "Tiêng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/v/n/vn_lotrwr_vert_main_2764x4096_intl_1_.jpg",
        trailer: "https://www.youtube.com/watch?v=_ra5S4RDcu8",
        status_id: 1,
    },
    {
        id: 23,
        name: `CAPTAIN AMERICA: THẾ GIỚI MỚI`,
        description: `Sau cuộc gặp gỡ với tân Tổng thống Hoa Kỳ Thaddeus Ross, Sam Wilson vô tình bị cuốn vào cuộc xung đột tại một sự kiện quốc tế. Trong vai trò Captain America mới, Wilson buộc phải điều tra và lật tẩy một âm mưu toàn cầu bất chính, trước khi kẻ thủ ác nhấn chìm cả thế giới vào cảnh suy tàn.`,
        release_date: `2025-02-14`,
        duration: 0,
        age_rating: "",
        genres: "Hành Động, Khoa Học Viễn Tưởng",
        directors: "Julius Onah",
        actors: "Harrison Ford, Anthoy Mackie, Giancarlo Esposito, Rosa Salazar, Seth Rollins, Shira Haas",
        lang: "Tiêng Anh",
        format: "2D",
        poster: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/c/a/captain_america_teaserdebut_1sht_vie.jpg",
        trailer: "https://www.youtube.com/watch?v=T-aJxCFUN_8",
        status_id: 1,
    },
];
