export const theaters = [
    {
        id: 1,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 1,
    },
    {
        id: 2,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 1,
    },
    {
        id: 3,
        name: "",
        format: "Deluxe",
        row: 5,
        col: 5,
        cinema_id: 1,
    },
    {
        id: 4,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 2,
    },
    {
        id: 5,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 2,
    },
    {
        id: 6,
        name: "",
        format: "Deluxe",
        row: 5,
        col: 5,
        cinema_id: 2,
    },
    {
        id: 7,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 3,
    },
    {
        id: 8,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 3,
    },
    {
        id: 9,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 4,
    },
    {
        id: 10,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 4,
    },
    {
        id: 11,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 5,
    },
    {
        id: 12,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 5,
    },
    {
        id: 13,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 6,
    },
    {
        id: 14,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 6,
    },
    {
        id: 15,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 7,
    },
    {
        id: 16,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 7,
    },
    {
        id: 17,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 8,
    },
    {
        id: 18,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 8,
    },
    {
        id: 19,
        name: "",
        format: "IMAX",
        row: 10,
        col: 20,
        cinema_id: 9,
    },
    {
        id: 20,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 9,
    },
    {
        id: 21,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 9,
    },
    {
        id: 22,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 9,
    },
    {
        id: 23,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 10,
    },
    {
        id: 24,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 10,
    },
    {
        id: 25,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 10,
    },
    {
        id: 26,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 11,
    },
    {
        id: 27,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 11,
    },
    {
        id: 28,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 11,
    },
    {
        id: 29,
        name: "",
        format: "4DX®",
        row: 10,
        col: 20,
        cinema_id: 11,
    },
    {
        id: 30,
        name: "Rạp 1",
        format: "Gold Class",
        row: 4,
        col: 4,
        cinema_id: 11,
    },
    {
        id: 31,
        name: "Rạp 2",
        format: "Gold Class",
        row: 4,
        col: 4,
        cinema_id: 11,
    },
    {
        id: 32,
        name: "",
        format: "Cine & Suite",
        row: 5,
        col: 7,
        cinema_id: 11,
    },
    {
        id: 33,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 12,
    },
    {
        id: 34,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 12,
    },
    {
        id: 35,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 12,
    },
    {
        id: 36,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 13,
    },
    {
        id: 37,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 13,
    },
    {
        id: 38,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 13,
    },
    {
        id: 39,
        name: "",
        format: "Gold Class",
        row: 4,
        col: 4,
        cinema_id: 13,
    },
    {
        id: 40,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 14,
    },
    {
        id: 41,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 14,
    },
    {
        id: 42,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 14,
    },
    {
        id: 43,
        name: "",
        format: "Starium",
        row: 15,
        col: 24,
        cinema_id: 14,
    },
    {
        id: 44,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 15,
    },
    {
        id: 45,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 15,
    },
    {
        id: 46,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 15,
    },
    {
        id: 47,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 16,
    },
    {
        id: 48,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 16,
    },
    {
        id: 49,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 16,
    },
    {
        id: 50,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 17,
    },
    {
        id: 51,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 17,
    },
    {
        id: 52,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 17,
    },
    {
        id: 53,
        name: "Rạp 1",
        format: "4DX®",
        row: 10,
        col: 20,
        cinema_id: 17,
    },
    {
        id: 54,
        name: "Rạp 2",
        format: "4DX®",
        row: 10,
        col: 20,
        cinema_id: 17,
    },
    {
        id: 55,
        name: "Rạp 1",
        format: "Starium",
        row: 15,
        col: 24,
        cinema_id: 17,
    },
    {
        id: 56,
        name: "",
        format: "Cine & Suite",
        row: 5,
        col: 7,
        cinema_id: 17,
    },
    {
        id: 57,
        name: "",
        format: "Cine & Suite",
        row: 5,
        col: 7,
        cinema_id: 17,
    },
    {
        id: 58,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 18,
    },
    {
        id: 59,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 18,
    },
    {
        id: 60,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 18,
    },
    {
        id: 61,
        name: "",
        format: "Premium",
        row: 5,
        col: 7,
        cinema_id: 18,
    },
    {
        id: 62,
        name: "",
        format: "Gold Class",
        row: 4,
        col: 4,
        cinema_id: 18,
    },
    {
        id: 63,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 19,
    },
    {
        id: 64,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 19,
    },
    {
        id: 65,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 19,
    },
    {
        id: 66,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 20,
    },
    {
        id: 67,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 20,
    },
    {
        id: 68,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 20,
    },
    {
        id: 69,
        name: "",
        format: "IMAX",
        row: 10,
        col: 20,
        cinema_id: 20,
    },
    {
        id: 70,
        name: "",
        format: "4DX®",
        row: 10,
        col: 20,
        cinema_id: 20,
    },
    {
        id: 71,
        name: "",
        format: "ULTRA 4DX®",
        row: 10,
        col: 20,
        cinema_id: 20,
    },
    {
        id: 72,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 21,
    },
    {
        id: 73,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 21,
    },
    {
        id: 74,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 21,
    },
    {
        id: 75,
        name: "Rạp 1",
        format: "IMAX",
        row: 10,
        col: 20,
        cinema_id: 21,
    },
    {
        id: 76,
        name: "Rạp 2",
        format: "Gold Class",
        row: 4,
        col: 4,
        cinema_id: 21,
    },
    {
        id: 77,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 22,
    },
    {
        id: 78,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 22,
    },
    {
        id: 79,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 22,
    },
    {
        id: 80,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 23,
    },
    {
        id: 81,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 23,
    },
    {
        id: 82,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 23,
    },
    {
        id: 83,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 24,
    },
    {
        id: 84,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 24,
    },
    {
        id: 85,
        name: "Rạp 3",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 24,
    },
    {
        id: 86,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 25,
    },
    {
        id: 87,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 25,
    },
    {
        id: 88,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 26,
    },
    {
        id: 89,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 26,
    },
    {
        id: 90,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 27,
    },
    {
        id: 91,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 27,
    },
    {
        id: 92,
        name: "Rạp 1",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 28,
    },
    {
        id: 93,
        name: "Rạp 2",
        format: "",
        row: 9,
        col: 12,
        cinema_id: 28,
    },
];
